version: '3'
services:
  tour-of-go:
    container_name: 'tour-of-go'
    user: $UID:$GID
    build:
      context: .
      args:
        UID: $UID
        GID: $GID
        UNAME: $UNAME
    tty: true
    working_dir: '/home/$UNAME/workspace'
    volumes:
      - ./workspace:/home/$UNAME/workspace
      - ~/.ssh:/home/$UNAME/.ssh